### ISSUE TITLE
 Suggest adding custom features to Gson for LocalDateTime and LocalDate

### ISSUE THREAD

**Issue by marklee1972** [GoodforGod/java-etherscan-api#18]
Since use com.google.gson.Gson to parse the json of Etherscan's api response.
However the error will appear:
 **_io.api.etherscan.error.ParseException: Unable to make field private final java.time.LocalDate java.time.LocalDateTime.date accessible: module java.base does not "opens java.time" to unnamed module @38d8f54a_**

The reason is at:
io.api.etherscan.core.impl.BasicProvider

Line 47:
**_this.gson = new Gson();_**

I change the below code to fix this issuse:
```
this.gson = new GsonBuilder()
                .registerTypeAdapter(LocalDateTime.class, (JsonSerializer<LocalDateTime>) (src, typeOfSrc, context) -> new JsonPrimitive(src.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))))
                .registerTypeAdapter(LocalDate.class, (JsonSerializer<LocalDate>) (src, typeOfSrc, context) -> new JsonPrimitive(src.format(DateTimeFormatter.ofPattern("yyyy-MM-dd"))))
                .registerTypeAdapter(LocalDateTime.class, (JsonDeserializer<LocalDateTime>) (json, type, jsonDeserializationContext) -> {
                    String datetime = json.getAsJsonPrimitive().getAsString();
                    return LocalDateTime.parse(datetime, DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
                }).registerTypeAdapter(LocalDate.class, (JsonDeserializer<LocalDate>) (json, type, jsonDeserializationContext) -> {
                    String datetime = json.getAsJsonPrimitive().getAsString();
                    return LocalDate.parse(datetime, DateTimeFormatter.ofPattern("yyyy-MM-dd"));
                }).create();
```

Maybe the best way is either update the source code or supply a custom features.

**Comment by GoodforGod** [comment]
Hello, thanks for the issue, I will look into it and thanks for the details and provided code!

**Comment by GoodforGod** [comment]
Can you please tell what is endpoint/method library fails and what JDK version you used?

**Comment by marklee1972** [comment]
> Can you please tell what is endpoint/method library fails and what JDK version you used?

Yep
JDK JavaSE-1.8(jdk17.0.1)
Both MAINNET and ROPSTEN are the same error.
When querying for a transaction, it happens.

_List<Tx> tx = api.account().txs(ADDRESS);_
